import type { Metadata } from 'next';
import Navigation from '../custom-solutions/Navigation';
import ContactSection from '../ContactSection';
import ContactExperience from './ContactExperience';
import { email, faqs, nextSteps, phone, preparation, reasons, strategyUrl, whatsappUrl } from './content';
import styles from './page.module.css';

const title = 'Contact Bizgenix | AI Solutions, Product Demos and Consulting';
const description = 'Contact Bizgenix to discuss AI products, custom solutions, business automation, analytics, integrations, corporate training or implementation support.';
export const metadata: Metadata = { title, description, openGraph: { title, description, type: 'website' }, twitter: { card: 'summary', title, description } };

export default function ContactPage() {
  return <div className={styles.page} id="top"><a href="#main-content" className={styles.skipLink}>Skip to content</a><Navigation activePath="/contact" /><main id="main-content">
    <ContactExperience />
    <section className={styles.softSection} aria-labelledby="next-title"><div className={`${styles.container} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>FROM FIRST HELLO TO A CLEAR PLAN</p><h2 id="next-title">What happens<br /><em>after you contact us?</em></h2></div><p>A practical process to understand your business, explore your options and agree on the right next step.</p></div><ol className={styles.journey}>{nextSteps.map(([name, copy], index) => <li key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{copy}</p></li>)}</ol></div></section>
    <section className={`${styles.container} ${styles.section} ${styles.prepareLayout}`} aria-labelledby="prepare-title"><div><p className={styles.eyebrow}>A LITTLE CONTEXT GOES A LONG WAY</p><h2 id="prepare-title">A better first<br /><em>conversation.</em></h2><p>You do not need a complete technical document before speaking with Bizgenix. A few details can help us understand your requirement faster.</p><div className={styles.note}><span aria-hidden="true">↗</span><p>Start with the business problem.<br /><strong>We’ll work through the technology together.</strong></p></div></div><ul className={styles.checklist}>{preparation.map((item, index) => <li key={item}><span aria-hidden="true">0{index + 1}</span>{item}</li>)}</ul></section>
    <section className={styles.whySection} aria-labelledby="why-title"><div className={`${styles.container} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>BUSINESS CONTEXT. TECHNICAL DEPTH.</p><h2 id="why-title">Why start a conversation<br /><em>with Bizgenix?</em></h2></div><p>From a focused product setup to a custom platform, we help connect your business priorities with a practical implementation path.</p></div><div className={styles.reasonGrid}>{reasons.map(([heading, copy], index) => <article key={heading}><span>0{index + 1}</span><h3>{heading}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className={`${styles.container} ${styles.section}`} aria-labelledby="connect-title"><div className={styles.connectPanel}><div><p className={styles.eyebrow}>VISIT OR CONNECT WITH BIZGENIX</p><h2 id="connect-title">Based in Ahmedabad.<br /><em>Connected to your business.</em></h2><p>Discovery, demos, development and support can be handled remotely. Contact the team to discuss an in-person meeting or an on-site engagement.</p><span className={styles.company}>Bizgenix AI Solutions Pvt. Ltd.</span></div><address className={styles.contactDetails}><a href={`mailto:${email}`}><span>GENERAL ENQUIRIES</span><strong>{email}</strong><b aria-hidden="true">↗</b></a><a href="tel:+918200858674"><span>SALES & DEMOS</span><strong>{phone}</strong><b aria-hidden="true">↗</b></a><a href={whatsappUrl('Hi Bizgenix, I would like to start a conversation about my business.')} target="_blank" rel="noopener noreferrer"><span>WHATSAPP</span><strong>Start a conversation</strong><b aria-hidden="true">↗</b></a></address></div></section>
    <section className={styles.softSection} aria-labelledby="faq-title"><div className={`${styles.container} ${styles.section} ${styles.faqLayout}`}><div><p className={styles.eyebrow}>BEFORE WE SAY HELLO</p><h2 id="faq-title">Good questions.<br /><em>Clear answers.</em></h2><p>Not sure where to start? Tell us about the challenge. We’ll help you find the right direction.</p><a className={styles.textLink} href={whatsappUrl("Hi Bizgenix, I would like to start a conversation about my business.")} target="_blank" rel="noopener noreferrer">Start a Conversation <span aria-hidden="true">↗</span></a></div><div className={styles.faqList}>{faqs.map(([question, answer]) => <details key={question} name="contact-faq"><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className={styles.finalCta} id="contact" aria-labelledby="final-title"><div className={styles.container}><p className={styles.eyebrow}>YOUR NEXT CHAPTER STARTS WITH A CONVERSATION</p><h2 id="final-title">Ready to find the right<br /><em>AI opportunity?</em></h2><p>Share your business challenge with Bizgenix. We will help you understand what can be automated, what should be integrated and which solution can create the strongest business impact.</p><div className={styles.actions}><a className={styles.primary} href={whatsappUrl("Hi Bizgenix, I would like to start a conversation about my business.")} target="_blank" rel="noopener noreferrer">Start a Conversation <span aria-hidden="true">↗</span></a><a className={styles.secondary} href={strategyUrl} target="_blank" rel="noopener noreferrer">Book an AI Strategy Session</a><a className={styles.textLink} href="#enquiry-options">Request a Product Demo <span aria-hidden="true">↗</span></a></div></div></section>
  </main><ContactSection homeHref="/" footerOnly /></div>;
}
