import type { Metadata } from 'next';
import Image from 'next/image';
import Navigation from '../custom-solutions/Navigation';
import ContactSection from '../ContactSection';
import CourseCatalog from './CourseCatalog';
import { communityUrl, corporateUrl, learningPaths, learningOutcomes, whyLearn, experience, learningJourney, corporateTopics, audiences, academyReasons, courseFaqs, enquire } from './content';
import styles from './page.module.css';

const title = 'Practical AI Courses, Workshops & Corporate Training | Bizgenix';
const description = 'Learn AI, prompt engineering, automation, AI agents, Voice AI and business intelligence through practical Bizgenix courses for owners, professionals, students and corporate teams.';
export const metadata: Metadata = { title, description, openGraph: { title, description, type: 'website' }, twitter: { card: 'summary', title, description } };

export default function CoursesPage() {
  return <div className={styles.page} id="top">
    <a className={styles.skipLink} href="#courses-main">Skip to content</a>
    <Navigation activePath="/courses" />
    <main id="courses-main">
      <section className={styles.hero} aria-labelledby="courses-title"><div className={`${styles.container} ${styles.heroLayout}`}>
        <div className={styles.heroCopy}><p className={styles.eyebrow}><span /> BIZGENIX ACADEMY</p><h1 id="courses-title">Learn AI that solves<br /><em>real business<br />problems.</em></h1><p className={styles.heroLead}>Practical skills. Real tools. Possibilities you can put to work.</p><p className={styles.description}>Build practical AI, automation and business transformation skills through hands-on courses designed for business owners, professionals, students and corporate teams.</p><div className={styles.actions}><a className={styles.primary} href="#featured-courses">Explore Courses <span aria-hidden="true">→</span></a><a className={styles.secondary} href={communityUrl} target="_blank" rel="noopener noreferrer">Join the AI Community <span aria-hidden="true">↗</span></a></div><ul className={styles.heroTraits}><li>Real business use cases</li><li>Hands-on learning</li><li>Skills you can apply</li></ul></div>
        <div className={styles.heroVisual}><div className={styles.visualHalo} aria-hidden="true" /><figure className={styles.heroPhoto}><div className={styles.photoHeader}><span>BIZGENIX / LEARNING IN ACTION</span><i aria-hidden="true">•••</i></div><Image src="/scale-with-ai/cohort-group.webp" alt="Participants learning together at a Bizgenix Scale With AI session" width={1600} height={1066} priority /><figcaption><span className={styles.captionIcon} aria-hidden="true">✦</span><div><strong>Learn together. Build with confidence.</strong><span>A community focused on practical AI adoption.</span></div></figcaption></figure><div className={styles.floatingNote}><span aria-hidden="true">✓</span><div>From learning<br /><strong>to doing.</strong></div></div><div className={styles.skillChips} aria-hidden="true"><span>AI &amp; prompts</span><span>Automation</span><span>Business impact</span></div></div>
      </div></section>
      <section className={styles.proof} aria-label="Bizgenix learning in numbers"><dl className={styles.container}>{[['2,000+', 'Professionals & business owners trained'], ['1,000+', 'AI community members'], ['110+', 'Live AI systems built'], ['Multiple cities', 'Ahmedabad, Surat, Mumbai · Vadodara upcoming']].map(([value, label]) => <div key={value}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
      <section className={`${styles.section} ${styles.container}`} id="featured-courses" aria-labelledby="catalog-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>FIND YOUR NEXT SKILL</p><h2 id="catalog-title">Practical courses.<br /><em>Real-world possibilities.</em></h2></div><p>Explore AI foundations, business applications and automation. Find a course that fits your experience and desired outcome.</p></div><CourseCatalog /></section>
      <section className={styles.softSection} id="learning-paths" aria-labelledby="paths-title"><div className={`${styles.section} ${styles.container}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>A PATH FOR EVERY AMBITION</p><h2 id="paths-title">Your role. Your goals.<br /><em>Your learning path.</em></h2></div><p>Start where you are. Build the skills that matter for your business, your career or your team.</p></div><div className={styles.pathGrid}>{learningPaths.map((path, index) => <article className={styles.pathCard} key={path.name}><span className={styles.pathNumber}>0{index + 1}</span><p className={styles.pathAudience}>{path.audience}</p><h3>{path.name}</h3><p>{path.description}</p><ul>{path.topics.map(topic => <li key={topic}>{topic}</li>)}</ul><a href={path.href}>{index === 3 ? 'Explore corporate training' : 'Explore courses'} <span aria-hidden="true">→</span></a></article>)}</div></div></section>
      <section className={`${styles.section} ${styles.container} ${styles.whyLayout}`} aria-labelledby="why-title"><div className={styles.splitHeading}><p className={styles.eyebrow}>WHY LEARN AI WITH BIZGENIX?</p><h2 id="why-title">Learn from people<br /><em>putting AI to work.</em></h2><p>AI is changing how businesses sell, communicate, analyse data and serve customers. Knowing a tool is only the beginning.</p><p>Our programs are created by people actively designing and deploying AI solutions for companies. Learn where AI fits, how to use it and how to measure the results.</p><div className={styles.learningFormula} aria-hidden="true"><span>Real tools</span><b>+</b><span>Real use cases</span><b>=</b><strong>Practical confidence</strong></div></div><ul className={styles.checkList}>{whyLearn.map(point => <li key={point}><span aria-hidden="true">✓</span>{point}</li>)}</ul></section>
      <section className={styles.outcomes} aria-labelledby="outcomes-title"><div className={`${styles.section} ${styles.container}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>WHAT YOU CAN LEARN</p><h2 id="outcomes-title">Skills that travel<br /><em>from class to work.</em></h2></div><p>Across our programs, explore the foundations, tools and frameworks behind practical AI adoption.</p></div><div className={styles.outcomeGrid}>{learningOutcomes.map(([name, detail], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{detail}</p></article>)}</div></div></section>
      <section className={`${styles.section} ${styles.container}`} aria-labelledby="experience-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>THE LEARNING EXPERIENCE</p><h2 id="experience-title">Build something useful.<br /><em>Take it with you.</em></h2></div><p>Go beyond theory with live examples, practical projects and resources you can apply to your work, business or career.</p></div><div className={styles.experienceGrid}>{experience.map(([name, detail], index) => <article key={name}><span className={styles.smallIcon} aria-hidden="true">{['▶', '↗', '▤', '◎', '✦', '···', '✓', '↻'][index]}</span><h3>{name}</h3><p>{detail}</p></article>)}</div></section>
      <section className={styles.softSection} aria-labelledby="journey-title"><div className={`${styles.section} ${styles.container}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>YOUR LEARNING JOURNEY</p><h2 id="journey-title">From your first step<br /><em>to everyday application.</em></h2></div></div><ol className={styles.journey}>{learningJourney.map(([name, detail], index) => <li key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{detail}</p></li>)}</ol></div></section>
      <section className={`${styles.section} ${styles.container}`} id="corporate-training" aria-labelledby="corporate-title"><div className={styles.corporatePanel}><div className={styles.splitHeading}><p className={styles.eyebrow}>CORPORATE AI TRAINING</p><h2 id="corporate-title">Stronger teams.<br /><em>Smarter ways to work.</em></h2><p>Customized training that helps your organization improve productivity, accelerate AI adoption and build common standards across teams.</p><div className={styles.formatTags}><span>Online</span><span>At your office</span><span>Hybrid</span></div><a className={styles.primary} href={corporateUrl} target="_blank" rel="noopener noreferrer">Discuss your team’s training <span aria-hidden="true">↗</span></a></div><div className={styles.corporateTopics}><p>BUILT AROUND YOUR BUSINESS</p><ul className={styles.checkList}>{corporateTopics.map(point => <li key={point}><span aria-hidden="true">✓</span>{point}</li>)}</ul></div></div></section>
      <section className={`${styles.section} ${styles.container}`} id="ai-community" aria-labelledby="community-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>LEARN TOGETHER. KEEP GROWING.</p><h2 id="community-title">More than a course.<br /><em>A community of doers.</em></h2></div><p>Keep discovering new tools, sharing ideas and exploring implementation opportunities through community discussions, updates and practical workshops.</p></div><div className={styles.cityGrid}>{[['Ahmedabad', 'ahmedabad'], ['Surat', 'surat'], ['Mumbai', 'mumbai']].map(([city, file]) => <figure key={city}><Image src={`/scale-with-ai/${file}.webp`} alt={`Participants at a Bizgenix AI workshop in ${city}`} width={800} height={600} /><figcaption><span>AI WORKSHOPS</span><strong>{city}</strong><span aria-hidden="true">↗</span></figcaption></figure>)}</div><div className={styles.communityBottom}><div><p>Practical sessions for business owners and professional communities, alongside corporate and industry workshops.</p></div><a className={styles.secondary} href={communityUrl} target="_blank" rel="noopener noreferrer">Join the AI Community <span aria-hidden="true">↗</span></a></div></section>
      <section className={styles.softSection} aria-labelledby="audience-title"><div className={`${styles.section} ${styles.container} ${styles.audienceLayout}`}><div className={styles.splitHeading}><p className={styles.eyebrow}>WHO CAN JOIN?</p><h2 id="audience-title">Curiosity is a<br /><em>great starting point.</em></h2><p>For anyone who wants practical AI skills. Most beginner courses need no coding experience; technical programs specify their recommended prerequisites.</p></div><ul className={styles.audienceTags}>{audiences.map(audience => <li key={audience}>{audience}</li>)}</ul></div></section>
      <section className={`${styles.section} ${styles.container}`} aria-labelledby="academy-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>THE BIZGENIX ACADEMY DIFFERENCE</p><h2 id="academy-title">Built on implementation.<br /><em>Focused on your progress.</em></h2></div></div><div className={styles.reasonGrid}>{academyReasons.map(([name, detail], index) => <article key={name}><span>0{index + 1}</span><div><h3>{name}</h3><p>{detail}</p></div></article>)}</div></section>
      <section className={styles.softSection} id="course-faqs" aria-labelledby="faq-title"><div className={`${styles.section} ${styles.container} ${styles.faqLayout}`}><div className={styles.splitHeading}><p className={styles.eyebrow}>A FEW THINGS YOU MAY BE WONDERING</p><h2 id="faq-title">Good questions.<br /><em>Clear answers.</em></h2><p>Need help choosing a course or planning training for your team?</p><a className={styles.primary} href={enquire('Bizgenix AI courses and learning paths')} target="_blank" rel="noopener noreferrer">Talk to our team <span aria-hidden="true">↗</span></a></div><div className={styles.faqList}>{courseFaqs.map(([question, answer], index) => <details key={question} name="course-questions" open={index === 0}><summary><span className={styles.faqNumber}>0{index + 1}</span>{question}<span className={styles.faqToggle} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></div></section>
      <section className={styles.finalCta} id="contact" aria-labelledby="course-contact-title"><div className={styles.container}><p className={styles.eyebrow}>YOUR NEXT CHAPTER STARTS HERE</p><h2 id="course-contact-title">Start your<br /><em>practical AI journey.</em></h2><p>Whether you want to automate your business, improve professional productivity, prepare for the future or train your team, Bizgenix has a practical learning path for you.</p><div className={styles.actions}><a className={styles.primary} href="#featured-courses">Explore All Courses <span aria-hidden="true">→</span></a><a className={styles.secondary} href={communityUrl} target="_blank" rel="noopener noreferrer">Join the AI Community <span aria-hidden="true">↗</span></a><a className={styles.textLink} href={corporateUrl} target="_blank" rel="noopener noreferrer">Book Corporate Training <span aria-hidden="true">↗</span></a></div></div></section>
    </main><ContactSection homeHref="/" footerOnly />
  </div>;
}
