import type { Metadata } from 'next';
import Link from 'next/link';
import Navigation from '../custom-solutions/Navigation';
import ContactSection from '../ContactSection';
import CountUp from '../CountUp';
import { ApproachExplorer, CapabilityExplorer, CommunityExplorer, IndustryExplorer } from './AboutExplorers';
import { differentiators, directors, impact, strategyUrl } from './content';
import styles from './page.module.css';

const title = 'About Bizgenix | Practical AI, Automation and Business Impact';
const description = 'Meet Bizgenix, an AI implementation and business automation company building intelligent products, custom solutions and practical AI education for Indian businesses.';
export const metadata: Metadata = { title, description, openGraph: { title, description, type: 'website' }, twitter: { card: 'summary', title, description } };

export default function AboutPage() {
  return <div className={styles.page} id="top"><a className={styles.skipLink} href="#main-content">Skip to content</a><Navigation activePath="/about" /><main id="main-content">
    <section className={styles.hero} aria-labelledby="about-title"><div className={`${styles.container} ${styles.heroLayout}`}><div className={styles.heroCopy}><p className={styles.eyebrow}><span className={styles.dot} />PEOPLE. AI. REAL IMPACT.</p><h1 id="about-title">Building AI that<br />solves <em>real business<br />problems.</em></h1><p className={styles.lead}>Bizgenix is an AI implementation and business automation company helping organizations transform the way they operate.</p><p className={styles.heroDescription}>We design intelligent systems that reduce manual work, automate repetitive processes, improve decision-making, and create measurable business outcomes.</p><div className={styles.actions}><a className={styles.primary} href={strategyUrl} target="_blank" rel="noopener noreferrer">Book a Free AI Strategy Session <span aria-hidden="true">↗</span></a><Link className={styles.textLink} href="/contact">Talk to Our Experts <span aria-hidden="true">↗</span></Link></div><p className={styles.heroFoot}>Our focus is not just on building AI, but on delivering solutions that create real business value.</p></div>
    </div></section>
    <nav className={styles.sectionNav} aria-label="Explore the About page"><div className={styles.container}><span>GET TO KNOW US</span>{[['Our story', '#our-story'], ['What we do', '#what-we-do'], ['Our approach', '#our-approach'], ['Our community', '#community'], ['Our founder', '#founder'], ['Our directors', '#directors']].map(([label, href]) => <a key={href} href={href}>{label}<span aria-hidden="true">↗</span></a>)}</div></nav>
    <section className={`${styles.container} ${styles.section} ${styles.storyLayout}`} id="our-story" aria-labelledby="story-title"><div><p className={styles.eyebrow}>OUR STORY</p><h2 id="story-title">The gap between<br />business challenges<br /><em>and better possibilities.</em></h2><div className={styles.storySignature}><span aria-hidden="true">↗</span><p>Practical by design.<br /><strong>Business-first by nature.</strong></p></div></div><div className={styles.storyCopy}><p>Businesses today generate huge amounts of data but still struggle with manual operations, disconnected software, delayed decisions, and inefficient workflows.</p><p>Bizgenix was founded to bridge this gap by combining <strong>Artificial Intelligence, Automation, Analytics, and Enterprise Technology</strong> into practical business solutions.</p><p>Rather than offering one-size-fits-all software, we work closely with every client to understand their processes, identify operational bottlenecks, and build AI-powered systems that improve efficiency, reduce costs, and accelerate growth.</p></div></section>
    <section className={`${styles.container} ${styles.purposeGrid}`} aria-label="Our mission and vision"><article><span className={styles.purposeSymbol} aria-hidden="true">◎</span><p className={styles.eyebrow}>OUR MISSION</p><h2>Make AI practical.<br /><em>Make progress measurable.</em></h2><p>Our mission is to make Artificial Intelligence practical, accessible, and measurable for businesses of every size. We aim to help organizations automate routine work, empower employees with intelligent tools, and build technology that drives long-term growth.</p></article><article><span className={styles.purposeSymbol} aria-hidden="true">↗</span><p className={styles.eyebrow}>OUR VISION</p><h2>A trusted partner.<br /><em>A lasting business impact.</em></h2><p>Our vision is to become India’s most trusted AI implementation partner by delivering innovative, scalable, and secure AI solutions that transform industries and create lasting business impact.</p></article></section>
    <section className={`${styles.container} ${styles.section}`} id="what-we-do" aria-labelledby="capability-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>THREE WAYS TO MOVE YOUR BUSINESS FORWARD</p><h2 id="capability-title">One partner.<br /><em>Connected capabilities.</em></h2></div><p>Ready-to-use products, custom AI solutions and everyday automation. Explore the approach that fits your business.</p></div><CapabilityExplorer /></section>
    <section className={styles.softSection} id="industries" aria-labelledby="industries-title"><div className={`${styles.container} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>BUILT AROUND YOUR WORLD</p><h2 id="industries-title">Different industries.<br /><em>Specific possibilities.</em></h2></div><p>We develop tailored AI solutions across industries. Select yours to explore the workflows and business needs we can help address.</p></div><IndustryExplorer /></div></section>
    <section className={`${styles.container} ${styles.section}`} aria-labelledby="difference-title"><div className={styles.differenceLayout}><div><p className={styles.eyebrow}>WHY BUSINESSES CHOOSE BIZGENIX</p><h2 id="difference-title">Built for confidence.<br /><em>Designed for impact.</em></h2><p>A practical implementation partner, from understanding the problem to helping your team put the solution to work.</p><Link className={styles.textLink} href="/contact">Let’s discuss your business <span aria-hidden="true">↗</span></Link></div><ol className={styles.differences}>{differentiators.map((name, index) => <li key={name}><span>0{index + 1}</span><h3>{name}</h3><b aria-hidden="true">✓</b></li>)}</ol></div></section>
    <section className={styles.approachSection} id="our-approach" aria-labelledby="approach-title"><div className={`${styles.container} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>FROM UNDERSTANDING TO IMPLEMENTATION</p><h2 id="approach-title">A clear path.<br /><em>Every step of the way.</em></h2></div><p>Explore our six-step approach, from your first business conversation to adoption and continuous improvement.</p></div><ApproachExplorer /></div></section>
    <section className={`${styles.container} ${styles.section}`} aria-labelledby="impact-title"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>THE BUSINESS IMPACT</p><h2 id="impact-title">Better systems.<br /><em>Better everyday outcomes.</em></h2></div><p>Our solutions help organizations improve how they work, serve customers and grow.</p></div><div className={styles.impactGrid}>{impact.map(([name, copy], index) => <article key={name}><span className={styles.impactIcon} aria-hidden="true">{['↗', '↻', '◎', '₹', '▥', '⤴'][index]}</span><h3>{name}</h3><p>{copy}</p></article>)}</div></section>
    <section className={styles.softSection} id="community" aria-labelledby="community-title"><div className={`${styles.container} ${styles.section}`}><div className={styles.communityLayout}><div><p className={styles.eyebrow}>AI EDUCATION & COMMUNITY</p><h2 id="community-title">Progress grows<br /><em>when it’s shared.</em></h2><p>Beyond implementation, Bizgenix actively promotes AI awareness through workshops, executive sessions, and community initiatives.</p><dl className={styles.communityStats}><div><dt>Professionals & business owners trained</dt><dd><CountUp value={2000} duration={900} /></dd></div><div><dt>Community members</dt><dd><CountUp value={1000} duration={900} /></dd></div></dl><p className={styles.expansion}><span aria-hidden="true">↗</span> EXPANDING TO VADODARA</p><Link className={styles.primary} href="/courses#ai-community">Explore our AI community <span aria-hidden="true">↗</span></Link></div><CommunityExplorer /></div></div></section>
    <section className={`${styles.container} ${styles.section} ${styles.founderLayout}`} id="founder" aria-labelledby="founder-title"><div><p className={styles.eyebrow}>THE VISION BEHIND BIZGENIX</p><h2 id="founder-title">Dr. CA <em>Umang Ratani</em></h2><p className={styles.founderLead}>Helping Indian businesses adopt AI in a practical and results-driven manner.</p><p>Bizgenix is led by Dr. CA Umang Ratani, whose vision is to help Indian businesses adopt AI in a practical and results-driven manner. By combining business strategy, financial expertise, and technology, he has guided organizations toward smarter operations and sustainable growth.</p><div className={styles.founderPillars}><span>Business strategy</span><span>Financial expertise</span><span>Technology</span></div><Link className={styles.textLink} href="/contact">Connect with our team <span aria-hidden="true">↗</span></Link></div></section>
    <section className={styles.softSection} id="directors" aria-labelledby="directors-title">
      <div className={`${styles.container} ${styles.section}`}>
        <div className={styles.sectionHeading}>
          <div><p className={styles.eyebrow}>OUR DIRECTORS</p><h2 id="directors-title">Experience that informs<br /><em>our direction.</em></h2></div>
          <p>Meet the directors bringing financial experience, strategic perspective and business leadership to Bizgenix.</p>
        </div>
        <div className={styles.directorGrid}>
          {directors.map(director => <article className={styles.directorProfile} key={director.id} aria-labelledby={`${director.id}-title`}>
            <p className={styles.eyebrow}>DIRECTOR</p>
            <h3 id={`${director.id}-title`}>{director.name}</h3>
            <p className={styles.directorFocus}>{director.focus}</p>
            <div className={styles.directorBio}>{director.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div>
            <ul className={styles.directorExpertise} aria-label={`${director.name}'s areas of expertise`}>{director.expertise.map(item => <li key={item}>{item}</li>)}</ul>
          </article>)}
        </div>
      </div>
    </section>
    <section className={styles.finalCta} id="contact" aria-labelledby="contact-title"><div className={styles.container}><p className={styles.eyebrow}>YOUR NEXT CHAPTER STARTS HERE</p><h2 id="contact-title">Let’s build<br /><em>the future together.</em></h2><p>Whether you’re exploring AI for the first time or scaling enterprise-wide automation, Bizgenix is ready to partner with you. Our team works alongside your business to design, build, deploy, and continuously improve AI solutions that deliver measurable results.</p><div className={styles.actions}><a className={styles.primary} href={strategyUrl} target="_blank" rel="noopener noreferrer">Book a Free AI Strategy Session <span aria-hidden="true">↗</span></a><Link className={styles.secondary} href="/contact">Contact Our Team <span aria-hidden="true">↗</span></Link></div></div></section>
  </main><ContactSection homeHref="/" footerOnly /></div>;
}
